FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    build-essential \
    libfftw3-dev \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir essentia psycopg2-binary numpy yt-dlp

COPY vector_audio.py .
COPY essentia-models/ ./essentia-models/

CMD ["python", "download_vectorize_audio.py"]
